modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="gennokiokuplus"
version="${file.jarVersion}"
displayName="GennokiokuPlus"
credits="Gennokioku"
displayURL="https://gennokioku.city/"
logoFile="logo.png"
authors="Coldshine"
description='''
GennokiokuPlus for Gennokioku server ONLY.
'''

[[dependencies.gennokiokuplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




