modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="stomtcraftplus"
version="2022.1.1"
displayName="GennokiokuPlus"
credits="Gennokioku"
displayURL="https://craft.stomt.world/"
logoFile="logo.png"
authors="Coldshine"
description='''
GennokiokuPlus for Gennokioku server ONLY.
'''

[[dependencies.stomtcraftplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




