/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package world.stomt.craft.plus;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsStomtcraftplusMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsStomtcraftplusMod() {
		sounds.put(new ResourceLocation("stomtcraftplus", "a_walk_in_the_rain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "a_walk_in_the_rain")));
		sounds.put(new ResourceLocation("stomtcraftplus", "he_xi_corridor"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "he_xi_corridor")));
		sounds.put(new ResourceLocation("stomtcraftplus", "ren_jian_feng_jing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "ren_jian_feng_jing")));
		sounds.put(new ResourceLocation("stomtcraftplus", "feeling_the_rain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "feeling_the_rain")));
		sounds.put(new ResourceLocation("stomtcraftplus", "qiu_zi_mei_nonakuqing_ni_in_the_autumn_sky"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "qiu_zi_mei_nonakuqing_ni_in_the_autumn_sky")));
		sounds.put(new ResourceLocation("stomtcraftplus", "du_juan_yuan_wu_qu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "du_juan_yuan_wu_qu")));
		sounds.put(new ResourceLocation("stomtcraftplus", "yi_xia_si_xiang"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "yi_xia_si_xiang")));
		sounds.put(new ResourceLocation("stomtcraftplus", "dancing_butterflies"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "dancing_butterflies")));
		sounds.put(new ResourceLocation("stomtcraftplus", "qiu_zi_mei_nonakuqing_ni"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "qiu_zi_mei_nonakuqing_ni")));
		sounds.put(new ResourceLocation("stomtcraftplus", "yan_yu_xing_zhou"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "yan_yu_xing_zhou")));
		sounds.put(new ResourceLocation("stomtcraftplus", "forbidden_love"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "forbidden_love")));
		sounds.put(new ResourceLocation("stomtcraftplus", "positive_outlook"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "positive_outlook")));
		sounds.put(new ResourceLocation("stomtcraftplus", "da_shang_hua_huo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "da_shang_hua_huo")));
		sounds.put(new ResourceLocation("stomtcraftplus", "dream_it_possible"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "dream_it_possible")));
		sounds.put(new ResourceLocation("stomtcraftplus", "jin_ling_yao"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "jin_ling_yao")));
		sounds.put(new ResourceLocation("stomtcraftplus", "fan_hua_chang_bian_luo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "fan_hua_chang_bian_luo")));
		sounds.put(new ResourceLocation("stomtcraftplus", "huan_qin"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "huan_qin")));
		sounds.put(new ResourceLocation("stomtcraftplus", "liu_nian_ru_ge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "liu_nian_ru_ge")));
		sounds.put(new ResourceLocation("stomtcraftplus", "gou_zhi_qi_shi"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "gou_zhi_qi_shi")));
		sounds.put(new ResourceLocation("stomtcraftplus", "hu_xin_ting_kan_xue"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "hu_xin_ting_kan_xue")));
		sounds.put(new ResourceLocation("stomtcraftplus", "sheng_cun_zai_mao_xian"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "sheng_cun_zai_mao_xian")));
		sounds.put(new ResourceLocation("stomtcraftplus", "suo_ni_ya_si_zhan_dou_shi"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "suo_ni_ya_si_zhan_dou_shi")));
		sounds.put(new ResourceLocation("stomtcraftplus", "with_an_orchid"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "with_an_orchid")));
		sounds.put(new ResourceLocation("stomtcraftplus", "end_dragon_survive_1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "end_dragon_survive_1")));
		sounds.put(new ResourceLocation("stomtcraftplus", "itumohe_du_demo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "itumohe_du_demo")));
		sounds.put(new ResourceLocation("stomtcraftplus", "tunajue_xing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "tunajue_xing")));
		sounds.put(new ResourceLocation("stomtcraftplus", "wen_koeteimasukapu_ranosheng"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("stomtcraftplus", "wen_koeteimasukapu_ranosheng")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsStomtcraftplusMod.ModElement.class)
					elements.add((ElementsStomtcraftplusMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsStomtcraftplusMod.ModElement::initElements);
		this.addNetworkMessage(StomtcraftplusModVariables.WorldSavedDataSyncMessageHandler.class,
				StomtcraftplusModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = StomtcraftplusModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = StomtcraftplusModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				StomtcraftplusMod.PACKET_HANDLER.sendTo(new StomtcraftplusModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				StomtcraftplusMod.PACKET_HANDLER.sendTo(new StomtcraftplusModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = StomtcraftplusModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				StomtcraftplusMod.PACKET_HANDLER.sendTo(new StomtcraftplusModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			StomtcraftplusMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsStomtcraftplusMod elements;
		protected final int sortid;
		public ModElement(ElementsStomtcraftplusMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
